config/routes.rb
Rails.application.routes.draw do
  resources :advertisements
  ActiveAdmin.routes(self)
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true

  default_scope { where(published: true) }

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :advertisor, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  def is_admin?
    self.email && ENV['ADMIN_EMAILS'].to_s.include?(self.email)
  end

end

app/controllers/advertisements_controller.rb
class AdvertisementsController < InheritedResources::Base

  private

    def advertisement_params
      params.require(:advertisement).permit(:user_id, :title, :description, :published)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_admin_user!
    redirect_to new_user_session_path unless current_user.try(:is_admin?)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advertisements/_form.html.slim
= simple_form_for(@advertisement) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user
    = f.input :title
    = f.input :description
    = f.input :published

  .form-actions
    = f.button :submit

app/views/advertisements/edit.html.slim
h1 Editing advertisement

== render 'form'

= link_to 'Show', @advertisement
'|
= link_to 'Back', advertisements_path

app/views/advertisements/index.html.slim
h1 Advertisements

table
  thead
    tr
      th Title
      th Description
      th Published
      th
      th
      th

  tbody
    - @advertisements.each do |advertisement|
      tr
        td = advertisement.title
        td = advertisement.description
        td = advertisement.published
        - if current_user.try(:admin?) || current_user.id == advertisement.user.id
          td = link_to 'Show', advertisement
          td = link_to 'Edit', edit_advertisement_path(advertisement)
          td = link_to 'Destroy', advertisement, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Advertisement', new_advertisement_path

app/views/advertisements/new.html.slim
h1 New advertisement

== render 'form'

= link_to 'Back', advertisements_path

app/views/advertisements/show.html.slim
p#notice = notice

p
  strong User:
  = @advertisement.user
p
  strong Title:
  = @advertisement.title
p
  strong Description:
  = @advertisement.description
p
  strong Is publised:
  = @advertisement.published

= link_to 'Edit', edit_advertisement_path(@advertisement)
'|
= link_to 'Back', advertisements_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li> <%= link_to 'Admin', admin_dashboard_path  %> </li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/nav_links_for_auth'

app/views/layouts/_navigation_links.html.erb
= render 'layouts/nav_links_for_auth'

app/views/layouts/_sidebar.html.slim
/! Sidebar
#sidebar-wrapper
  ul.sidebar-nav
    li.sidebar-brand
      a href="#"
        | RAO
    li
      =link_to 'Advertisement', advertisements_path if user_signed_in?
    li
      a href="#"  About
    li
      a href="#"  Contact

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Rao'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Rao'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      #wrapper
        == render 'layouts/sidebar.html'
        == render 'layouts/messages'
        == yield

/! Menu Toggle Script
javascript:
  $("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
  });

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>Simple Sidebar</h1>
                <p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>
                <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
                <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
            </div>
        </div>
    </div>
</div>
<!-- /#page-content-wrapper -->